language: python
python:
  - 2.7

git:
  submodules: false

before_install:
  - rm -rf plugin.video.elementum
  - git clone https://github.com/elgatito/elementum-binaries.git resources/bin/
  # - git submodule init
  # - git submodule update --depth=22

install:
  - pip install -r requirements.txt

script:
  - flake8
  - ./scripts/xgettext.sh
  - make
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "${TRAVIS_TAG}" ]; then
      make zipfiles
    fi

# deploy:
#   provider: releases
#   api_key: $GH_TOKEN
#   file:
#     - plugin.video.elementum-${TRAVIS_TAG:1}.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.android_arm.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.android_arm64.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.android_x86.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.darwin_x86.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.darwin_x64.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.ios_arm64.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.ios_arm-7.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.linux_arm-6.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.linux_arm-7.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.linux_arm64.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.linux_x64.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.linux_x86.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.windows_x64.zip
#     - plugin.video.elementum-${TRAVIS_TAG:1}.windows_x86.zip
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true
